[package]
name = "wpconfig"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
log = "0.4"
pretty_env_logger = "0.5"
dotenv = "0.15.0"
